### PR TITLE
Proposed new nuker model

### PR DESCRIPTION
**Pull request by Gadjung**
Nuker

proposed model, can show both Energy and Ghodium levels

### CODE REVIEW

**Comment by thmsndk** [comment]
I like it!, the ghodium levels is in the nuke head, correct?

While on the subject of nukes this issue has a branch about actually visualizing them
https://github.com/thmsndk/Screeps3D/issues/58 
You can see a missile here on the way down into the ground here
image

Would love an actual missile model instead of the simple think I've whacked together there xD

**Comment by Gadjung** [comment]
Yes ghodium level is a hexagonal prism inside of head. i have idea of making it as a sphere though

My thought was that model can go to master branch, and from there be pulled into #58 branch (so it does not need to wait till issue 58 is merged).
Can move the model to merge directly to #58 if You'd prefer.

**Comment by thmsndk** [comment]
@Gadjung for sure, the nuker model itself needs to go into the develop branch, I just mentioned the other branch in case you wanted to make a new PR with a missile model for this branch https://github.com/thmsndk/Screeps3D/tree/feature/visualize_nuke_arc :D

**Comment by Gadjung** [comment]
Nuker_v2_3_4

New proposition for nukers added

**Comment by thmsndk** [comment]
@Gadjung i guess the pointy one should not have an orb inside it, but should instead be a, euhmm "cone" that filles it up in the same shape as the glass. while the pointy one looks the "most" as the official one, atleast from the side
image
This is the original 3D model for comparison
image

**Pull request merged**
