### PR TITLE
New mineral models

### PR DESCRIPTION
**Pull request by Gadjung**

### CODE REVIEW

**Comment by Gadjung** [comment]
New mineral models will separate them and set material color to blank
MAterials

**Comment by thmsndk** [comment]
Looks awesome, in the current implementation, the mineral scales in size based on amount left, is the mineral itself detached from the "base" you currently render?

**Comment by Gadjung** [comment]
yes the rock base is separate from mineral itself.
one thing, for better look i used smooth shading, but all should look still good on flat if smooth is not supported.

if all is good i'll create the last models for Commodities in this style

**Comment by Gadjung** [comment]
MAterials_2
added Deposits also

**Comment by Gadjung** [comment]
new oxygen mineral model : 
image

**Pull request merged**
