### PR TITLE
New Factory models based on old design

### PR DESCRIPTION
**Pull request by Gadjung**
One out of 3 models needs to be selected, i did not check how it looks after importing to Unity.
Cogwheel on each model is separate object that can rotate.

Any comments welcome

### CODE REVIEW

**Comment by thmsndk** [comment]
Image

So far I prefer the big one to the left, all the others seems small and squashed, especially if I think in regards to scale compared with other structures and creeps.

While I kinda like the dome on the top for energy, i'm not sure how it makes it look from top-down view, in general we've tried to keep models in such a way that they look / feel like the top-down view in the official client, just with a third dimension and details. I'm sure others also have an opinion. All in all I like the tall one on the left the most.

**Comment by tcdejong** [comment]
I made the current placeholder, so might not be completely unbiased. That said, I prefer the left one too. The current one is already small compared to storage etc, so it definitely shouldn't become smaller. 

Perhaps we can still do something like the multiple fins on the right most models to indicate the factory `level` property? Energy in the top dome, and the windows for commodity contents?

**Comment by Gadjung** [comment]
ok, i'll follow-up with the most left-one.
i can change the sphere to cuboid (that can either represent energy, resources, product or all mentioned) to make it more distinct from spawn/extensions

**Comment by Gadjung** [comment]
Updated models according to feedback. brought design to follow up closer with top-view from screeps in one version

Factory_Prev2

**Comment by Robalian** [comment]
I like the more spiky ones. If bars on top of the cog are level indicators I'd pick the top left one. Nice work ;]

**Comment by Gadjung** [comment]
my ideas was that : 
- spikes would be for level indications
- rectangle/half circular bars would be for indicating resource
though spike as ornament + bars on top as level indicator sounds nice also, depends if its doable in code (did not look there yet

**Comment by Gadjung** [comment]
another approach will be taken

**Pull request closed without merging**
