### PR TITLE
Scaling of size/visibility for source based on energy left

### PR DESCRIPTION
**Pull request by thmsndk**
- [x] Scale source based on energy available
- [ ] Align source better with terrain so you can see low amount source nodes.

image
image
image

Animated: (200 mb .gif)
https://www.dropbox.com/s/xvy9oo7dg5pq8q0/source-visibility-remaining-energy.gif?dl=1

### CODE REVIEW

**Comment by AlinaNova21** [comment]
So, just a tip: use mp4 rather than a 200mb gif ;)

**Comment by thmsndk** [comment]
well, the program I used to record the gif (LICEcap) records gifs xD usually it works pretty well, but yeah, should probably find something else for longer "videos" :)

**Comment by thmsndk** [comment]
I need to find a better way to scale visibility so a large part of the resource node is still present when 50% energy or more is left.

**Comment by thmsndk** [comment]
🤔 We also have an issue in regards to sources being rendered inside walls, becomes more apparent due to the scaling of the model i've made.

image

Should we be scaling the transparancy of the object instead of the size? render the source randomly further up in the air? generate less walls around a source?

Any ideas?

**Comment by Robalian** [comment]
Maybe make it cover more and more in "depleted source" texture

**Comment by thmsndk** [comment]
So kinda like the creeps, containers and such, make it like a transparent container that is filled with resources?

**Comment by Robalian** [comment]
I thought more shiny vs dark, and mask wouldn't go from top to bottom, but in a noise pattern.

**Comment by thmsndk** [comment]
i've changed the curve for scalability to be like this currently
image

But I think we should explore the ideas you have :)

**Pull request merged**
