### PR TITLE
Sk lairs

### PR DESCRIPTION
**Pull request by Robalian**

### CODE REVIEW

**Comment by Robalian** [comment]
#18

**Comment by thmsndk** [comment]
What checkboxes does this PR check from that issue? And would you consider it as closing the issue?

**Comment by Robalian** [comment]
All of info panel, advanced model. Maybe glowing red, but currently it's subtle, I might want to improve it. Visualizing next spawn time is not done.

**Comment by thmsndk** [comment]
I'm currently on mobile, feel free to update the issue and merge this @Robalian ☺

**Pull request merged**
