### PR TITLE
fix for fix for subscribing to too many rooms

### PR DESCRIPTION
**Pull request by Robalian**
but now also outside of editor

### CODE REVIEW

**Comment by Sir-nk** [comment]
ya u just need to turn it off n on agian i think bbro 🤔

**Comment by Robalian** [comment]
am I doing something incorrectly? D:

**Comment by Sir-nk** [comment]
lol

**Comment by Robalian** [comment]
Seriously though. Never done PRs before

**Review by thmsndk — APPROVED** [review]

**Pull request merged**
