### PR TITLE
Skybox v2

### PR DESCRIPTION
**Pull request by Gadjung**
Feel free to look around and check - some adjustments are still to be done - open for suggestions

Known issues:
- lamps on sources sometimes behave funky when rotating camera
- lamps on sources sometimes give funky look when source is in funky place (like single diagonal access)
- floor still shines with too much spec during day
- floor have some `shining pixels` - it's a feature obtained from dividing textures makes it look more space-like
- powerbank material is not adjusted fully (supernova at some angles)
- badge colors are sometimes incorrect (emission to fix)
- controller + mineral + source looks funny in SWC E2S18 -> Ask Roballion about solving this

### CODE REVIEW

**Comment by thmsndk** [comment]
Is it supposesd to look like this before launch?
image

**Comment by Gadjung** [comment]
nope, looks normal for me (at least on main PC, will see in a moment on 2nd)

**Comment by thmsndk** [comment]
Hmm the teleport out effect does not seem to trigger on creeps :/ the teleport in effect seems to do that though, even though it looks smaller than I remember
image

**Comment by Gadjung** [comment]
1st thing - Game scene looks like Your screenshot on 2nd pc but works fine

Portal thing - did not know there's some effect on creep teleporting - as of now it's static (no change of effect when teleporting creep - can update/revert thouhg)

**Comment by thmsndk** [comment]
The road prefab that we use to "select" probably needs to have material changed to the the same as the road used in roadnetwork, or we need to toggle the "base" in the prefab off when not in place constructionmode 🤔 
image

**Comment by thmsndk** [comment]
Hmm getting this

```
MissingReferenceException: The object of type 'ScaleVisibility' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Common.BaseVisibility.SetVisibility (System.Single target, System.Boolean instant) (at Assets/Scripts/Common/BaseVisibility.cs:47)
Common.BaseVisibility.SetVisibility (System.Boolean show, System.Boolean instant) (at Assets/Scripts/Common/BaseVisibility.cs:37)
Common.BaseVisibility.Hide (System.Boolean instant) (at Assets/Scripts/Common/BaseVisibility.cs:75)
Screeps3D.Rooms.Views.MapDotView.Hide () (at Assets/Scripts/Screeps3D/Rooms/Views/MapDotView.cs:49)
Screeps3D.Rooms.Views.MapView.ClearDots () (at Assets/Scripts/Screeps3D/Rooms/Views/MapView.cs:161)
Screeps3D.Rooms.Views.MapView.OnMapData (JSONObject data) (at Assets/Scripts/Screeps3D/Rooms/Views/MapView.cs:60)
Screeps3D.Rooms.RoomMapStream.ReceiveData (JSONObject Data) (at Assets/Scripts/Screeps3D/Rooms/RoomMapStream.cs:54)
Screeps_API.ScreepsSocket.FindSubscription (JSONObject json) (at Assets/Scripts/Screeps_API/ScreepsSocket.cs:142)
Screeps_API.ScreepsSocket.ProcessMessage (WebSocketSharp.MessageEventArgs e) (at Assets/Scripts/Screeps_API/ScreepsSocket.cs:127)
Screeps_API.ScreepsSocket.Update () (at Assets/Scripts/Screeps_API/ScreepsSocket.cs:102)

```

**Comment by thmsndk** [comment]
Having to click the middle / blue part of the wall (source) is not intuitive, we should probably add a collider that matches the "source" model e.g. the yellow. it also seems like the emission is wrong during "day" it's 1500/3000 and it seems like it is "empty" atleast based on it not being "lit" 🤔 

image

**Comment by thmsndk** [comment]
Also got this, might have to do with selecting the source?
```
MissingReferenceException: The object of type 'ScaleAxes' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Common.BaseVisibility.SetVisibility (System.Single target, System.Boolean instant) (at Assets/Scripts/Common/BaseVisibility.cs:47)
Screeps3D.Tools.Selection.Subpanels.CapacityPanel.UpdateLabel () (at Assets/Scripts/Screeps3D/Tools/Selection/Subpanels/CapacityPanel.cs:36)
Screeps3D.Tools.Selection.Subpanels.CapacityPanel.OnDelta (JSONObject obj) (at Assets/Scripts/Screeps3D/Tools/Selection/Subpanels/CapacityPanel.cs:44)
Screeps3D.RoomObjects.RoomObject.RaiseDeltaEvent (JSONObject delta) (at Assets/Scripts/Screeps3D/RoomObjects/RoomObject.cs:57)
Screeps3D.RoomObjects.RoomObject.Delta (JSONObject delta, Screeps3D.Rooms.Room room) (at Assets/Scripts/Screeps3D/RoomObjects/RoomObject.cs:50)
Screeps3D.Rooms.RoomUnpacker.UnpackObjects (JSONObject roomData) (at Assets/Scripts/Screeps3D/Rooms/RoomUnpacker.cs:81)
Screeps3D.Rooms.RoomUnpacker.Unpack (JSONObject roomData) (at Assets/Scripts/Screeps3D/Rooms/RoomUnpacker.cs:29)
Screeps3D.Rooms.RoomObjectStream.ReceiveData (JSONObject Data) (at Assets/Scripts/Screeps3D/Rooms/RoomObjectStream.cs:54)
Screeps_API.ScreepsSocket.FindSubscription (JSONObject json) (at Assets/Scripts/Screeps_API/ScreepsSocket.cs:142)
Screeps_API.ScreepsSocket.ProcessMessage (WebSocketSharp.MessageEventArgs e) (at Assets/Scripts/Screeps_API/ScreepsSocket.cs:127)
Screeps_API.ScreepsSocket.Update () (at Assets/Scripts/Screeps_API/ScreepsSocket.cs:102)
```

**Comment by Gadjung** [comment]
regarding scale-axis error - no idea, will check
source - can put collider of height 3 to match whole part or just put it at source level
source color - as of now resource left in source is scaling down light of attached lamp, should not influence at all the emission of material (except when it's empty) - will take a look

**Comment by thmsndk** [comment]
I just pushed a fix to develop that should prevent the "overlapping" roads from both the RoadNetwork and the RoomObject road

**Comment by thmsndk** [comment]
Are theese the shining pixels?
image

**Comment by thmsndk** [comment]
Swamps seems to not be rendered? in latest version?
image
image

It's the "famous" ghost wall room on 40,24  the swamp below the controller 🤔

**Comment by thmsndk** [comment]
Got this in shard3 W31S42, could that be the reason swamps are not rendering? or is it something else?
```
IndexOutOfRangeException: Index was outside the bounds of the array.
Screeps3D.Rooms.Views.TerrainView.generateWalls2 () (at Assets/Scripts/Screeps3D/Rooms/Views/TerrainView.cs:303)
Screeps3D.Rooms.Views.TerrainView.Deform () (at Assets/Scripts/Screeps3D/Rooms/Views/TerrainView.cs:401)
Common.Scheduler.Update () (at Assets/Scripts/Common/Scheduler.cs:35)
```

**Comment by Gadjung** [comment]
i think this one is caused by close-to-edge placement of powerbank 
`foreach (var pos in _powerBankPositions)
            {
                for (int x = -1; x <= 1; ++x)
                    for (int y = -1; y <= 1; ++y)
                        wallHeight[pos.x + x, pos.y + y] = Math.Min(wallHeight[pos.x + x, pos.y + y], 0.35f + getRandom(pos.x + x, pos.y + y) * 0.25f);
            }`

and that's strange since that's not highway room

**Comment by Gadjung** [comment]
> Are theese the shining pixels?
> image

yes :)
it gives nice space look-like right ? (have no idea how to fix it so trying to ship-it as a feature)

**Comment by thmsndk** [comment]
@Gadjung was mineral rendering fixed as well? :)

**Pull request merged**
